//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace demo.ws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReservationByIdClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReservationByIdReceptionistOperationCompleted;
        
        private System.Threading.SendOrPostCallback addReservationOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateReservationOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteReservationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::demo.Properties.Settings.Default.demo_ws_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getCompletedEventHandler getCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event getReservationByIdClientCompletedEventHandler getReservationByIdClientCompleted;
        
        /// <remarks/>
        public event getReservationByIdReceptionistCompletedEventHandler getReservationByIdReceptionistCompleted;
        
        /// <remarks/>
        public event addReservationCompletedEventHandler addReservationCompleted;
        
        /// <remarks/>
        public event updateReservationCompletedEventHandler updateReservationCompleted;
        
        /// <remarks/>
        public event deleteReservationCompletedEventHandler deleteReservationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get(string userName) {
            object[] results = this.Invoke("get", new object[] {
                        userName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAsync(string userName) {
            this.getAsync(userName, null);
        }
        
        /// <remarks/>
        public void getAsync(string userName, object userState) {
            if ((this.getOperationCompleted == null)) {
                this.getOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOperationCompleted);
            }
            this.InvokeAsync("get", new object[] {
                        userName}, this.getOperationCompleted, userState);
        }
        
        private void OngetOperationCompleted(object arg) {
            if ((this.getCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCompleted(this, new getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User login(string user, string password) {
            object[] results = this.Invoke("login", new object[] {
                        user,
                        password});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string user, string password) {
            this.loginAsync(user, password, null);
        }
        
        /// <remarks/>
        public void loginAsync(string user, string password, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        user,
                        password}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getReservationByIdClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Reservation[] getReservationByIdClient(int id) {
            object[] results = this.Invoke("getReservationByIdClient", new object[] {
                        id});
            return ((Reservation[])(results[0]));
        }
        
        /// <remarks/>
        public void getReservationByIdClientAsync(int id) {
            this.getReservationByIdClientAsync(id, null);
        }
        
        /// <remarks/>
        public void getReservationByIdClientAsync(int id, object userState) {
            if ((this.getReservationByIdClientOperationCompleted == null)) {
                this.getReservationByIdClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReservationByIdClientOperationCompleted);
            }
            this.InvokeAsync("getReservationByIdClient", new object[] {
                        id}, this.getReservationByIdClientOperationCompleted, userState);
        }
        
        private void OngetReservationByIdClientOperationCompleted(object arg) {
            if ((this.getReservationByIdClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReservationByIdClientCompleted(this, new getReservationByIdClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getReservationByIdReceptionist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Reservation[] getReservationByIdReceptionist(int id) {
            object[] results = this.Invoke("getReservationByIdReceptionist", new object[] {
                        id});
            return ((Reservation[])(results[0]));
        }
        
        /// <remarks/>
        public void getReservationByIdReceptionistAsync(int id) {
            this.getReservationByIdReceptionistAsync(id, null);
        }
        
        /// <remarks/>
        public void getReservationByIdReceptionistAsync(int id, object userState) {
            if ((this.getReservationByIdReceptionistOperationCompleted == null)) {
                this.getReservationByIdReceptionistOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReservationByIdReceptionistOperationCompleted);
            }
            this.InvokeAsync("getReservationByIdReceptionist", new object[] {
                        id}, this.getReservationByIdReceptionistOperationCompleted, userState);
        }
        
        private void OngetReservationByIdReceptionistOperationCompleted(object arg) {
            if ((this.getReservationByIdReceptionistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReservationByIdReceptionistCompleted(this, new getReservationByIdReceptionistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addReservation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addReservation(int idClient, int idReceptionist, string idRoom, string reservationName, string arrivalDate, int nights) {
            object[] results = this.Invoke("addReservation", new object[] {
                        idClient,
                        idReceptionist,
                        idRoom,
                        reservationName,
                        arrivalDate,
                        nights});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addReservationAsync(int idClient, int idReceptionist, string idRoom, string reservationName, string arrivalDate, int nights) {
            this.addReservationAsync(idClient, idReceptionist, idRoom, reservationName, arrivalDate, nights, null);
        }
        
        /// <remarks/>
        public void addReservationAsync(int idClient, int idReceptionist, string idRoom, string reservationName, string arrivalDate, int nights, object userState) {
            if ((this.addReservationOperationCompleted == null)) {
                this.addReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddReservationOperationCompleted);
            }
            this.InvokeAsync("addReservation", new object[] {
                        idClient,
                        idReceptionist,
                        idRoom,
                        reservationName,
                        arrivalDate,
                        nights}, this.addReservationOperationCompleted, userState);
        }
        
        private void OnaddReservationOperationCompleted(object arg) {
            if ((this.addReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addReservationCompleted(this, new addReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateReservation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool updateReservation(int id, int idClient, string idRoom, string reservationName, string arrivalDate, int nights) {
            object[] results = this.Invoke("updateReservation", new object[] {
                        id,
                        idClient,
                        idRoom,
                        reservationName,
                        arrivalDate,
                        nights});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void updateReservationAsync(int id, int idClient, string idRoom, string reservationName, string arrivalDate, int nights) {
            this.updateReservationAsync(id, idClient, idRoom, reservationName, arrivalDate, nights, null);
        }
        
        /// <remarks/>
        public void updateReservationAsync(int id, int idClient, string idRoom, string reservationName, string arrivalDate, int nights, object userState) {
            if ((this.updateReservationOperationCompleted == null)) {
                this.updateReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateReservationOperationCompleted);
            }
            this.InvokeAsync("updateReservation", new object[] {
                        id,
                        idClient,
                        idRoom,
                        reservationName,
                        arrivalDate,
                        nights}, this.updateReservationOperationCompleted, userState);
        }
        
        private void OnupdateReservationOperationCompleted(object arg) {
            if ((this.updateReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateReservationCompleted(this, new updateReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteReservation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool deleteReservation(int id) {
            object[] results = this.Invoke("deleteReservation", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void deleteReservationAsync(int id) {
            this.deleteReservationAsync(id, null);
        }
        
        /// <remarks/>
        public void deleteReservationAsync(int id, object userState) {
            if ((this.deleteReservationOperationCompleted == null)) {
                this.deleteReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteReservationOperationCompleted);
            }
            this.InvokeAsync("deleteReservation", new object[] {
                        id}, this.deleteReservationOperationCompleted, userState);
        }
        
        private void OndeleteReservationOperationCompleted(object arg) {
            if ((this.deleteReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteReservationCompleted(this, new deleteReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User {
        
        private int idField;
        
        private string emailField;
        
        private string passwordField;
        
        private string nameField;
        
        private TypeUser typeField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public TypeUser Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TypeUser {
        
        /// <remarks/>
        Client,
        
        /// <remarks/>
        Receptionist,
        
        /// <remarks/>
        NotFound,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Room {
        
        private int idField;
        
        private string typeRoomField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string priceField;
        
        private string urlPhotoField;
        
        private bool availableField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string TypeRoom {
            get {
                return this.typeRoomField;
            }
            set {
                this.typeRoomField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string UrlPhoto {
            get {
                return this.urlPhotoField;
            }
            set {
                this.urlPhotoField = value;
            }
        }
        
        /// <remarks/>
        public bool Available {
            get {
                return this.availableField;
            }
            set {
                this.availableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Reservation {
        
        private int idField;
        
        private int idClientField;
        
        private int idRecepcionistField;
        
        private Room roomField;
        
        private string nameField;
        
        private string arrivalDateField;
        
        private int nightsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int IdClient {
            get {
                return this.idClientField;
            }
            set {
                this.idClientField = value;
            }
        }
        
        /// <remarks/>
        public int IdRecepcionist {
            get {
                return this.idRecepcionistField;
            }
            set {
                this.idRecepcionistField = value;
            }
        }
        
        /// <remarks/>
        public Room Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ArrivalDate {
            get {
                return this.arrivalDateField;
            }
            set {
                this.arrivalDateField = value;
            }
        }
        
        /// <remarks/>
        public int Nights {
            get {
                return this.nightsField;
            }
            set {
                this.nightsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void getCompletedEventHandler(object sender, getCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void getReservationByIdClientCompletedEventHandler(object sender, getReservationByIdClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReservationByIdClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReservationByIdClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Reservation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Reservation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void getReservationByIdReceptionistCompletedEventHandler(object sender, getReservationByIdReceptionistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReservationByIdReceptionistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReservationByIdReceptionistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Reservation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Reservation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void addReservationCompletedEventHandler(object sender, addReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void updateReservationCompletedEventHandler(object sender, updateReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void deleteReservationCompletedEventHandler(object sender, deleteReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591